### ISSUE TITLE
Can't JPro be works with GraalVM -> Natvie-image feature?

### ISSUE THREAD

**Issue by ctoabidmaqbool** [JPro-one/JPro-tickets#148]
Hi Devs! In the world of `Java` new technology is coming out e.g. [GraalVM](https://www.graalvm.org/). And It have a nice feature called **native-image**. 

Many Apps, Technologies and Companies are using `GraalVM -> native-image` feature. E.g. Gluon is using GraalVM in it's products to make native apps for desktop, android, ios and many other platforms.

Can't JPro benefits from GraalVM. Is it currently possible or any chances to use GraalVM in feature?

What you think about this.

**Comment by FlorianKirmaier** [comment]
You can't really use native-image, because the internal JPro classes are loaded in a separate classloader.
But if you could use it - the only benefit you would gain is a faster start time.
Because as a warmed-up JVM is usually as fast as GraalVM. Because the server is started usually before the user uses it, this wouldn't improve much.
