### ISSUE TITLE
Issue with Java 12.0.1

### ISSUE THREAD

**Issue by JasonWeise** [JPro-one/JPro-tickets#20]
Hi
I have configure JavaFX as per settings at https://openjfx.io/ with Java 12 as per instructions on site.
I then configured a Gradle project and all this runs as expected and shows the fxml file.

I then created a JPro-one project with the same files and am receiving the following error as soon a Gradle performs its build:
```
BUILD FAILED in 0s
Unexpected Java-Version (System.getProperty): 12.0.1
```

Is JPro-one not compatible with the latest Java and JavaFX environments?
Is there a way to get this to work at all, I'd love to demo JPro-one to my colleague?

Thanks in advance.

**Comment by FlorianKirmaier** [comment]
Thank you for the bug report.
JPro should work fine with Java12, but it seems like the current version of our Maven and Gradle plugin doesn't support it properly. This will be fixed in the next release, which will be released very soon.

JPro currently does not support JavaFX12, we will stick for now with the LTS-Version 11, so we can focus more on new features. But that shouldn't be a problem, because close to nothing has changed in the API of JavaFX.

**Comment by FlorianKirmaier** [comment]
The latest release is published which supports Java12
