### ISSUE TITLE
TableView & Label issues

### ISSUE THREAD

**Issue by Hugolarson** [JPro-one/JPro-tickets#55]
Sorting by left click on header does not work like in native JavaFX. Right click sorts but it also shows the TableView Context Menu. Not pretty.

TableView Header font does not look same like in native JavaFX. I think it related to that Label in general look different (bigger) in JPro. Not nice.

Hope that your goal is to make JPro behave and look like native JavaFX.

**Comment by FlorianKirmaier** [comment]
**Sorting:**
I can't confirm the issue with the TableView.  Sorting with left click work for me. You can also disable the browser context menu by setting `fxContextMenu=true` in the JProTag.

**Fonts:**
Which OS are you using?
On mac, there are currently some native fonts used which are not supported by the browsers - which causes problems you've described. The issue depends on the used fonts and doesn't happen when deploying to a Linux server.

**Comment by Hugolarson** [comment]
Sorting:
I set fxContextMenu=true.
Can you left click on column to sort in ControlsFx demo on jpro.one? Impossible. I have tried on Edge and Chrome on several Windows computers.

Font:
Right is native FX Windows 10.
Left JPro deployed on Ubuntu 20 showed in Chrome Windows 10. JPro font is bigger and more grayish than black.
![image](https://user-images.githubusercontent.com/8046614/84637006-729d9b80-af1f-11ea-9a64-46568f7c65ad.png)

**Comment by FlorianKirmaier** [comment]
TableView:
I can now confirm the issue in the latest version. We are gonna look into it.

Fonts:
JavaFX by default loads the default font of the OS.
That's why it looks different depending on the OS.
JPro must look the same on all OS/Browsers. Everything else is considered a bug.
We plan to make sure JPro uses the same font on all operating systems.
It wasn't the highest priority, because it usually doesn't matter in production.

It Strange that the font of "kategori" seems to be darker on the second image which looks wrong, but We can not they more about it, without looking into it in detail.

**Comment by FlorianKirmaier** [comment]
TableView:
We were able to reproduce and fix the problem! Thank you for the report!
It was a regression in `2019.2.4`.
The versions `2019.2.3` and `2019.2.5-SNAPSHOT` are working now.

**Comment by Hugolarson** [comment]
TableView sorting seems to be working now. Good.

Font:
I discovered something strange.
Observe the image i pasted before.
The left is TableView header when TableView is shown in JFoenix JFXDialog.
When I show the TablwView in Stage with WebAPI.openStageAsTab the Font looks the same as native FX.
JFXDialog seems to change Font appearance of Lable with JPro.

**Comment by Hugolarson** [comment]
This issue is in JFoenix we discovered.
