### ISSUE TITLE
Option key / @ character on OSX

### ISSUE THREAD

**Issue by timoreichen** [JPro-one/JPro-tickets#6]
It's not possible to enter a '@' on macOS.
And using the option-button a banner is popping up showing your App Id.
Keyboard Layout: ch de. Not working on any Version of macOS so far including Mojave/Sierra, high Sierra. Safari and Chrome where tested.

**Comment by FlorianKirmaier** [comment]
Hi @timoreichen 
That issue is limited to apps, opened with the URL `http://<server>/test/fullscreen/appname`.
The jpro-tag has the following attribute, which should be removed: `showinfobyalt="true"`

You can copy the sourcecode of the page to resources/jpro/html/index.html, remove `showinfobyalt="true"` and open the server directly without any path: `http://<server>.
Then it should work properly.

I keep the ticket open, until we've reworked that feature.

**Comment by FlorianKirmaier** [comment]
showinfobyalt is no longer used, so i close the ticket.
