### ISSUE TITLE
openStageAsXxxx new issues

### ISSUE THREAD

**Issue by Hugolarson** [JPro-one/JPro-tickets#62]
Since 2019.2.5 I think something is broken.
When opening a heavy stage the entire application becomes unresponsive and some times I see a OUTOFMEMORY message in console.
Opening the Pane in a JFXDialog works fine.

**Comment by FlorianKirmaier** [comment]
Hm, this sounds interesting.
My first thought is, that it's unlikely that something in JPro broke, but one never knows.
We've introduced some openXXXAsXXX methods, but we didn't change the implementation of the older methods.

Did you test it with 2019.2.4? It would be very valuable for us to know whether this is restricted to the latest release.
It also might be a bug in the application which is hard to tell from the available information. It also might be introduced through a change in the application instead of a change in the JPro update.
There might be subtle differences in the application-logic when it's shown in a new Stage instead of the JFXDialog.

Does it relate to the size of the scenegraph of the stage? Does it also happen with an empty Stage?
If you could reproduce the bug in a simple application, then it would be very easy for us to fix it.

**Comment by Hugolarson** [comment]
Found the problem/bug.

stage.setMaximized(true) together with TableView cause this crazy JPro crash.
It makes the application unresponsive until JPro restart.
Remove setMaximized or TableView and it works.

Check my test project FxMain class line 85

[JproTest.zip](https://github.com/JPro-one/JPro-tickets/files/4929783/JproTest.zip)

**Comment by FlorianKirmaier** [comment]
Thank you for the test-class!
What's happening is, that JPro has a virtual monitor, which is seen by the application. This monitor is oversized, so the application doesn't think it's limited by size. Which has the effect, that the application gets gigantic after maximize, which leads to an extremely big TableView which leads to an increased memory usage.
So this is kind of the expected behaviour. Maybe we should disable maximize, because it doesn't make a lot of sense with JPro.

**Comment by Hugolarson** [comment]
Want to add that it's problematic that JPro crash/freeze this way without any hint in logs which makes it very difficult to debug.

**Comment by FlorianKirmaier** [comment]
Hm, it told you it ran out of memory. In retrospect, this is exactly what happened.

**Comment by Hugolarson** [comment]
I saw the OUTOFMEMORY one time but I think that was something else.
If you run my project you will not see OUTOFMEMORY on crash.
