### ISSUE TITLE
Will JPro works on all linux os?

### ISSUE THREAD

**Issue by ashokkumarvel** [JPro-one/JPro-tickets#65]
After releasing JPro , I runned the  restart.sh file from bin folder. It worked smoothly on ubuntu .

But , I have some doubts in deploying JPro on linux.

After releasing JPro ,

-  If  I didn't  install javafx on linux os will JPro work?

-  if I didn't install gtk2-engines on linux os will JPro work?

-  if I didn't install java jdk on linux os will JPro work?

I asked this questions. Because , I have some doubts in this [doc][1] . 

After releasing JPro , **Can I deploy JPro in all linux os ?**

  [1]: https://www.jpro.one/?page=docs/current/2.7/PREPARING_LINUX_FOR_JPRO

**Comment by FlorianKirmaier** [comment]
Nowadays JavaFX is just a java library and therefore cannot be installed, only be used by an application.
Unless you are using Java8 which also isn't really recommended nowadays.

JavaFX requires GTK. There might be some other setups possible but the solutions we've documented are the easiest solutions.

JavaJDK will always be required, but that shouldn't be a problem?

"All Linux" is quite a broad statement because there are so many variations. 
Maybe you should tell us more about what you want to do?

**Comment by abiange** [comment]
I want to publish  my project's released  JPro zip in my blog.

If the user download the published  zip and run that  Will the JPro  server work on all linux os?

**Comment by ashokkumarvel** [comment]
I want to publish  my project's released  JPro zip in my blog.

If the user download the published  zip and run that  Will the JPro  server work on all linux os?

**Comment by ashokkumarvel** [comment]
If the user run the restart.sh file from bin folder will JPro server work?

**Comment by FlorianKirmaier** [comment]
JPro works on all Linux-Versions which are supported by JavaFX - which should be the vast majority.
Note that it also required to install the proper JDK version, which should be JDK 11 in most cases.
Using Java8 can be tricky because some JDK providers on Linux decided to skip JavaFX. This problem doesn't exist with JavaFX11, because it's now only a library, so I would recommend using 11.

**Comment by poorvajappja** [comment]
If the user didn't install java jdk will JPro server work?

**Comment by ashokkumarvel** [comment]
If the user didn't install java jdk will JPro server work?

**Comment by FlorianKirmaier** [comment]
No, it won't work. The zip created by JPro requires a preinstalled JDK of the correct version (8 or 11+ dependent of the application)

**Comment by ashokkumarvel** [comment]
There is any way to deploying JPro without JDK?

I mean , there is any way to add JDK 11 feature inside the released zip ?

**Comment by ashokkumarvel** [comment]
How Can I use Jlink to overcome this problem?

**Comment by FlorianKirmaier** [comment]
It's nontrivial to use Jlink with JPro. JPro internally creates classloaders, and JPro also requires a special start-script + folder structure to work. It's not trivial to change this.
JPro usually runs on some kind of server and is not run on the local machine of the end users - which is why we thought our current solution is fine.
A simple solution, to run on any Linux system could be to just run it with docker: https://www.jpro.one/?page=docs/current/2.8/DOCKER_WITH_JPRO
You could also add the JDK to the zip itself and either adapt the start-script of JPro or instruct your users to add it to the $PATH variable.
