### ISSUE TITLE
An error occurred while getting the module name on Jpro

### ISSUE THREAD

**Issue by liangshp** [JPro-one/JPro-tickets#77]
##project description
      My project is based on java11 and consists of multiple modules.

##project issue
      The runtime needs to get a module name, which is available on JDK run, but not on JPRO run.
![_20200909100839](https://user-images.githubusercontent.com/18733048/92546210-9e14f580-f284-11ea-81db-e69084b46d1a.png)
     "classType.getModule().getName()" is null, Causes the project to run incorrectly
![_20200909100246](https://user-images.githubusercontent.com/18733048/92545875-b33d5480-f283-11ea-9393-89fadb056a50.png)

##test
  Try printing module name, I could not get the custom modules name(Show only the JDK module name)
![_20200909102222](https://user-images.githubusercontent.com/18733048/92547010-7d4d9f80-f286-11ea-90b5-16f85e534a44.png)
![_20200909102612](https://user-images.githubusercontent.com/18733048/92547241-08c73080-f287-11ea-884e-4be246ba2bd1.png)

  How to solve the above problems? Looking forward to your reply. Thank you!

**Comment by FlorianKirmaier** [comment]
The problem is, that JPro is using the normal classpath instead of the modulepath.
Basically JPro isn't using the module Feature of Java11.
To fix the problem, either you have to stop using the JavaAPI which directly works with the modules or we will provide you with a version of JPro, which uses the modulepath instead of the classpath.
Currently, you should be able to use all the modules of the JDK, but you won't be able to use reflection for the modules.

**Comment by liangshp** [comment]
> The problem is, that JPro is using the normal classpath instead of the modulepath.
> Basically JPro isn't using the module Feature of Java11.
> To fix the problem, either you have to stop using the JavaAPI which directly works with the modules or we will provide you with a version of JPro, which uses the modulepath instead of the classpath.
> Currently, you should be able to use all the modules of the JDK, but you won't be able to use reflection for the modules.

Thank you very much！
