### ISSUE TITLE
permessage-deflate websocket extension isn't supported on all container hosts (eg Azure)

### ISSUE THREAD

**Issue by pl4nty** [JPro-one/JPro-tickets#79]
JPro tries to establish a websocket at `/app/0!default`, but uses `Sec-WebSocket-Extensions: permessage-deflate`. This extension isn't supported with some container hosts, specifically Azure Web App Linux Containers in my case. An option is needed to disable this feature.

**Comment by FlorianKirmaier** [comment]
I assume the proxy of azure doesn't support it.
What does currently happens? Does JPro not work in this case?
Does it work when SSL is used? We usually recommend to always use SSL in production, 
which usually fixes problems, with Proxies not properly supporting some kind of web-features,
which especially happens with some proxy-configurations used by some companies.

But probably permessage-deflate doesn't make sense at all, because the messages are already compressed/decompressed in the JS/Java code of JPro.

**Comment by pl4nty** [comment]
Yeah the `permessage-deflate` header didn't make sense to me either. With some more research I found that there are issues with Azure's CORS/auth proxy and `permessage-deflate`. Azure's native SSL is proxied so no luck there, but I managed to get it working over HTTP with CORS/auth disabled.

It's just a test app so I'm not worried about SSL yet, but how would you recommend deploying it for a docker container?

**Comment by FlorianKirmaier** [comment]
I'm not sure about your docker environment. Maybe your cloud-provider gives some solutions for SSL. 
We usually use Nginx on the host to provide SSL. If you are controlling the host with the dockercontainer, you should be able to do the same.
