### ISSUE TITLE
Box around tooltips is always too small

### ISSUE THREAD

**Issue by mipastgt** [JPro-one/JPro-tickets#88]
The box around tooltips is always too small. Also for smaller texts than the one in the example.
This was tested on macOS 10.15.7 with JPro: 2020.1.5. This behaviour is the same on Firefox and on Chrome.

<img width="387" alt="Bildschirmfoto 2021-04-13 um 20 52 11" src="https://user-images.githubusercontent.com/16735714/114605845-cccfd000-9c9a-11eb-8a85-1788ca3f78df.png">

**Comment by FlorianKirmaier** [comment]
This issue only happens when using Mac. This happens because the fonts used by mac are often not supported by the browser. 
The width of the the default font is wider as the font used by JavaFX.
In production, this doesn't happen, because then usually no mac is used.

Should really prioritize the issue, because seems like everyone is running into it once.

**Comment by FlorianKirmaier** [comment]
Finally - fix will be released with 2021.2.2 and can be tested with the SNAPSHOT build.
With the upcoming version - JPro will no longer use the system font (which sometimes are not supported by the browser), and will choose the Font independent of the OS.
