### ISSUE TITLE
Unable to listen jpro-one server at 0.0.0.0 instead of localhost?

### ISSUE THREAD

**Issue by ctoabidmaqbool** [JPro-one/JPro-tickets#89]
Last time I was facing problem, e.g. How to deploy jPro-one server at Heroku.
I was put question at stack overflow : [How to deploy JPro-one JavaFx App on Heroku server?](https://stackoverflow.com/questions/67046887/how-to-deploy-jpro-one-javafx-app-on-heroku-server)

I somehow, deploy it at Heroku server successfully without any errors.

But, I think, it's listening at localhost:8080 and I need to listen it at 0.0.0.0 as Heroku server can't listen to localhost.
It's mentioned [here](https://dzone.com/articles/akka-http-from-zero-to-heroku-in-10-minutes). How can I do it ?

I was follow [HelloJPro](https://github.com/JPro-one/HelloJPro) Tutorial with JDK >= 11

Let me know, if you need any info. Thanks in advanced.

**Comment by FlorianKirmaier** [comment]
i don' think JPro binds to localhost.
I've checked the used address with `sudo lsof -i -P | grep LISTEN`
The output looked like this on Linux
```
java       738          ubuntu  287u  IPv6  25322      0t0  TCP *:8084 (LISTEN)
```
I've checked the PlayFramework (which uses akka-http internally) and it seems they bind to `0.0.0.0` by default.

I've made a helloworld-heroku project some time ago: https://github.com/FlorianKirmaier/JPro-Heroku
(It's not promoted, because its not really maintained)

What's the exact issue you are encountering?

**Comment by ctoabidmaqbool** [comment]
@FlorianKirmaier Thanks ,you very much Sir! Using your provided sample project e.g. [Jpro-Heroku](https://github.com/FlorianKirmaier/JPro-Heroku) I have solved my problem.
Actually I was trying trying using Gradle commands on Heroku With Apt-build packs.
In your project, you are using Container build pack, that's actually I was looking for, thanks again. Have a nice day.

**Comment by ctoabidmaqbool** [comment]
Using, Provided project e.g. https://github.com/FlorianKirmaier/JPro-Heroku. I have solved my problem.
Actually no need of listen to 0.0.0.0, however Heroku Container App can works on this already using port 80.
